ideal_width            = 79
max_width              = 79

fn_single_line         = true
struct_lit_width       = 50
struct_variant_width   = 50

reorder_imports        = false
reorder_imported_names = true

chain_base_indent      = 'Visual'
chain_indent           = 'Visual'
chains_overflow_last   = false
